services:
  db-clinica:
    image: postgres:16-alpine
    container_name: db-clinica
    restart: unless-stopped
    environment:
      POSTGRES_DB: clinica_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - db_clinica_data:/var/lib/postgresql/data

volumes:
  db_clinica_data:
