server:
  port: 8086

spring:
  application:
    name: clinica-backend
  datasource:
    url: jdbc:postgresql://localhost:5438/clinica_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
